### PR TITLE
Kogge-Stone adder

### PR DESCRIPTION
**Pull request by hakonhagland**
Preliminary version. Currently, the test case gives error:

```
Gate name: ij_G_2 type Or driven by too many other gates, including one from gate: ij_z_1_1
  Chip.java:0394:compileGate
  Chip.java:0632:compileChip
  Chip.java:0751:simulate
  Chip.java:0748:simulate
  Chip.java:4496:test_binary_kogge_stone
  Chip.java:5286:oldTests
  Chip.java:5325:newTests
  Chip.java:5331:main
```

### CODE REVIEW

**Comment by philiprbrenan** [comment]
This occurs when there is a name collision. I think you need to add more name indexing:  two gates have the same name and so it appears that they are one gate.  The current handling of this problem is not very effective: so far my efforts to improve it have not helped much.

**Comment by philiprbrenan** [comment]
I have not tested this but:

    final Bits G_next = bits(n(output, "G_next"), B);                                          // Result bits
    final Bits P_next = bits(n(output, "G_next"), B);  

generates the same name twice for different gates?  Each gate should have a separate name.  At the same time I need to allow forward declarations. It is one of those things that needs to be fixed but so far has not been annoying enough to warrant the time ...

**Comment by hakonhagland** [comment]
> generates the same name twice for different gates

Thanks! Fixed in latest commit.

**Comment by hakonhagland** [comment]
> Gate name: ij_G_2 type Or driven by too many other gates

Does this mean that we cannot reuse a Gate for a another calculation once it is previous value is not needed anymore? So each time we reuse a Gate it will accumulate inputs to the previous inputs. 

In the Python script however, we can reuse the G and G_next variables for each iteration, as the previous values are no longer needed..

**Comment by philiprbrenan** [comment]
Yes - gates can only used to do a specific calculation - they cannot be reused elsewhere. All the gates are active all the time, responding to any changes to their inputs immediately.  If the inputs to the chip do not change eventually all the gates stabilize in a fixed state as in the ripple adder  They have no sense of now I am doing calculation A, now B, just: have there been any changes to my inputs?  If  you have two calculations to do you have to generate two sets of gates.  So they cannot be reused spatially.  However, they can be reused in time by using a register. A register takes a snap shot of the state of the chip in one place at a point in time determined by a pulse and then applies that snapshot continuously else where on the chip to drive a further set of changes through the gates.  So, we might take a snapshot at the end of the loop, put it in a register,  then let the register drive the start of the for loop body to get the gates to change to their new inputs representing the next iteration of the for loop.

As you can see, registers and pulses represent a new layer of complexity: for these reasons it is much easier to unroll the for loops and just write out all the calculations they have to do linearly. And if this seems time consuming, then use Perl, or Python or Java to write the code you want to execute. You can use for loops in the generator, just not in the generated code!

**Comment by philiprbrenan** [comment]
In the following, we have an inner for loop (i)  and an outer one (step). May I suggest that gates defined inside the inner loop (i) might need to have ``n(step, i, output, "g1")``  etc. so that each iteration defines gates with different names? At the end of the inner loop, the  gates so created can be collapsed as shown in ``andBits()`` etc.   

```
    int step = 1;
    while (step < B) {
        for (int i = step; i < B; i++) {
            Gate g1 = And(n(i, output, "g1"), P.b(i), G.b(i-step+1));
            Or(G_next.b(i+1), G.b(i+1), g1);
            And(P_next.b(i+1), P.b(i+1), P.b(i-step+1));
        }
        for (int i = step; i < B; i++) {
            Bit  zi = Zero(n(step, i, output, "z"));
            Or(G.b(i+1), G_next.b(i+1), zi);
            Or(P.b(i+1), P_next.b(i+1), zi);
        }
        step *= 2;
    }
```

**Comment by hakonhagland** [comment]
@philiprbrenan Latest commit commit shows a new approach. Still preliminary, since I get warnings like:

```
Xor gate ij_2 does not drive any gate
  Chip.java:0414:compileGate
  Chip.java:0667:compileChip
  Chip.java:0790:simulate
  Chip.java:0787:simulate
  Chip.java:4617:test_binary_add_kogge_stone
  Chip.java:5405:newTests
  Chip.java:5411:main
```

**Comment by hakonhagland** [comment]
@philiprbrenan Seems like you were spot on regarding the annealing of the sum output :) All tests passes here now..

**Comment by hakonhagland** [comment]
@philiprbrenan Can you check if it O(log N) also? It seems promising to me :)

**Comment by philiprbrenan** [comment]
Performance of Kogge Stone Adder versus Ripple Adder on ``-2 + -2`` in number of steps:

```
Bits____  KogStone    Ripple
       2         4         5
       4         4        10
       8         4        18
      16         4        35
      32         4        67
```

**Comment by hakonhagland** [comment]
> Performance of Kogge Stone Adder versus Ripple Adder

@philiprbrenan Thanks for the comparison, but I think the steps for Kogge-Stone should not be constant we increasing bit widths. See #6  for a possible fix

**Pull request merged**
