### PR TITLE
Need to use distinct inputs to the adders

### PR DESCRIPTION
**Pull request by hakonhagland**
Need to use distinct inputs to the adders even if we add the same number

### CODE REVIEW

**Comment by philiprbrenan** [comment]
I see:
```
Bits____  KogStone    Ripple
       2         4         5
       4         5        10
       8         5        18
      16         5        35
      32         6        67
```
But I am not yet sure why this is happening.  Any ideas?

**Comment by philiprbrenan** [comment]
When the same input is being added to itself at 2 bits wide there are 21 gates in the KS adders versus 31 gates when different sources are being added. The extra gates are due to the fan out the constants used to construct the inputs to the bits strings to be added increasing the number of steps.  I conclude that it is safe to add the same set of bits to itself, although of course, it would be preferable to use shift left in this situation as it will be even faster.

**Comment by hakonhagland** [comment]
> Any ideas?

@philiprbrenan If the same reference is input for both numbers in `binaryAddKoggeStone("ka", kn, kn)` both `in1` and `in2` will have the same name here:

https://github.com/philiprbrenan/com.AppaApps.Silicon/blob/544ed3b3e515094aca2ef48fae51d6d7d4c89bcf/Chip.java#L1970

then I observed that the Xor() at line 1976:

https://github.com/philiprbrenan/com.AppaApps.Silicon/blob/544ed3b3e515094aca2ef48fae51d6d7d4c89bcf/Chip.java#L1976

will return a `Zero` operator instead of an `Xor` operator since the names are equal, see line 591:

https://github.com/philiprbrenan/com.AppaApps.Silicon/blob/544ed3b3e515094aca2ef48fae51d6d7d4c89bcf/Chip.java#L591

that was as far as I debugged it.

**Comment by philiprbrenan** [comment]
I think you have neatly explained why there are fewer gates in the **same input** version as shown by ``say(r)``. I am impressed by your debugging skills and also by the code I wrote on line 591 that I had forgotten all about!  In summary, in the **same input version** some of the gates get optimized away producing a shorter path that does not occur with the different inputs version.

**Pull request merged**
