### PR TITLE
First version of Brent-Kung adder

### PR DESCRIPTION
**Pull request by hakonhagland**
Currently, the test cases passes! I will next check the time complexity of the method..

### CODE REVIEW

**Comment by hakonhagland** [comment]
Sorry for messing up the diff with formatting changes. I reformatted the Kogge-Stone indentation according to the style used for the rest of the code

**Comment by hakonhagland** [comment]
Added a comparison with Kogge-Stone. When I run this comparison, I get warnings like this:

```
 Chip: binary_add_brent_kung_vs_kogge_stone  Step: 3 # Gates: 31  Maximum distance: 5  MostCountedDistance: 4  CountAtMostCountedDistance: 10
```

**Comment by philiprbrenan** [comment]
That looks likes you are using *say(c)* to print the state of the chip and
it is getting mixed up with your output ?

**Comment by hakonhagland** [comment]
> That looks likes you are using *say(c)* to print the state of the chip

Yes, indeed! I removed the say in the last commit, here is the result I get from the comparison now:

```
Bits____  BrentKung  KogStone
       2         4         4
       4         5         4
       8         6         4
      16         7         4
      32         8         5
```
As expected from the discussion in the [video](https://youtu.be/JmKuhglL88c?list=TLPQMzAwNzIwMjT9nh1P3mAfYQ) the Brent-Kung is a little bit slower then Kogge-Stone

**Comment by philiprbrenan** [comment]
```
Bits____  BrentKung  KogStone
       2         4         4
       4         5         4
       8         6         4
      16         7         4
      32         8         5
```

I will see if this further accelerates the Ban.java implementation of RiscV

**Pull request merged**
